# Generated by Django 6.0 on 2025-12-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('MONO', 'моно_букеты'), ('MIXED', 'сборные_букеты'), ('GIFT', 'подарочные_наборы'), ('COMP', 'композиции'), ('WEDDING', 'свадебные_букеты'), ('BUSINESS', 'деловые_букеты')], max_length=20, null=True, verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
