# Generated by Django 6.0 on 2025-12-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_product_updated_at_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
