# Generated by Django 6.0 on 2025-12-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MONO', '#моно_букеты'), ('MIXED', '#сборные_букеты'), ('GIFT', '#подарочные_наборы'), ('COMP', '#композиции'), ('WEDDING', '#свадебные_букеты'), ('BUSINESS', '#деловые_букеты')], default=1, help_text='Выберите тип букета', max_length=20, verbose_name='Категория товара'),
            preserve_default=False,
        ),
    ]
