# Generated by Django 6.0 on 2025-12-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('MONO', '#моно_букеты'), ('MIXED', '#сборные_букеты'), ('GIFT', '#подарочные_наборы'), ('COMP', '#композиции'), ('WEDDING', '#свадебные_букеты'), ('BUSINESS', '#деловые_букеты')], help_text='Выберите тип букета', max_length=20, null=True, verbose_name='Категория товара'),
        ),
    ]
