# Generated by Django 6.0 on 2025-12-06 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отображается ли товар в каталоге', verbose_name='Активный товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Доступное количество товара', verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('NOPAID', 'Неоплачен'), ('PAID', 'Оплачен'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELED', 'Отменен')], default='NEW', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
