# Generated by Django 6.0 on 2025-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_order_quantity_order_total_price_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PAID', 'Оплачен'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELED', 'Отменен')], default='NEW', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
